Repository UMC-HKT-Team-R/BE, pull requests merged in 2025-01, with the labels that each got.

#12 Feat/10
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/uiDesigner.xml
  Midnight-Snacker/.gradle/8.11.1/checksums/checksums.lock
  Midnight-Snacker/.gradle/8.11.1/checksums/md5-checksums.bin
  Midnight-Snacker/.gradle/8.11.1/checksums/sha1-checksums.bin
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/MidnightSnackerApplication.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/apiPlayload/exception/ExceptionAdvice.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/apiPlayload/exception/GeneralException.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/calender$calenderBuilder.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/calender.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/category.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/categoryCount.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/common/BaseEntity.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/enums/Color.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/enums/Status.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/member$memberBuilder.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/member.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/post$postBuilder.class
  Midnight-Snacker/out/production/classes/com/example/Midnight/Snacker/domain/post.class
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Calender.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Category.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/CategoryCount.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Comment.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Member.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Post.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/post.java
Labels: feat

#16 [fix/15] 오류 수정
  .github/workflows/dev_deploy.yml
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/PostController.java
Labels: bug

#22 [Fix] 생성순 조회
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/repository/CalendarRepository.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/security/principal/PrincipalDetails.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarServiceImpl.java
Labels: fix

#28 [Feat] 추천 api 구현
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/apiPayload/code/status/SuccessStatus.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/RecommendService/RecommendService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/RecommendService/RecommendServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/RecommendController.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/recommendDTO/RecommendResponseDTO.java
Labels: feat

#30 [Fix] 캘린더 등록하기 다 param 으로 변수 바꾸기
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/converter/CalendarConverter.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/CalendarController.java
Labels: fix

#33 [Feat] 충돌일어난거나 해결함
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/MidnightSnackerApplication.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Calendar.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/repository/MemberRepository.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/MemberService/MemberServiceImpl.java
Labels: feat

#34 충돌 고침
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/CalendarController.java
Labels: feat

#39 [Feat] merge
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/apiPayload/code/status/SuccessStatus.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Post.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/PostController.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/PostDTO/PostInfoDTO.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/PostDTO/PostRequestDTO.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/PostDTO/PostResponseDTO.java
Labels: feat

#42 [Feat] 캘린더 월별, 일별 조회 api 구현
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/apiPayload/code/status/ErrorStatus.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/apiPayload/exception/CalendarException.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/repository/CalendarRepository.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CalendarService/CalendarServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/CalendarController.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/CalendarDTO/CalendarResponseDTO.java
Labels: bug, feat

#43 [Feat] complete
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/apiPayload/code/status/SuccessStatus.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/domain/Comment.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/repository/CommentRepository.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/repository/PostRepository.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/CommentService/CommentServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostService.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/PostController.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/CommentDTO/CommentResponseDTO.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/PostDTO/PostResponseDTO.java
Labels: feat

#45 Feat/35
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/service/PostService/PostServiceImpl.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/controller/CalendarController.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/CommentDTO/CommentResponseDTO.java
  Midnight-Snacker/src/main/java/com/example/Midnight/Snacker/web/dto/PostDTO/PostResponseDTO.java
Labels: feat
